In [1]:
import pandas as pd
import numpy as np
import math
from copy import deepcopy 
from itertools import chain
from sklearn.metrics import mean_squared_error

In [2]:
from scipy.misc import derivative

In [24]:
derivative(sigmoid, -5, dx=1e-6)

0.006648056671571673

In [3]:
def derivative_sigmoid(x):
    e = math.exp((-1)*x)
    return e / ((1+e)**2)

In [25]:
derivative_sigmoid(-5)

0.006648056670790155

In [4]:
class NeuralNetwork:
    
    def __init__(self, neurals_input, weights, biases, functions, real_values, derivatives=None):
            
        if type(neurals_input) != list:
            raise Exception("Input must be a list")
        
        if not all(type(el) == list for el in neurals_input):
            
            if any(type(el) == list for el in neurals_input):
                raise Exception("Neurals_input is incorrectly formatted")
            
            neurals_input = [neurals_input]
        
        self.neurals_input = neurals_input
        
        self.weights = weights
        self.biases = biases
        self.functions = functions
        self.real_values = real_values
        self.a_values = []
        self.neuron_values = []
        self.e_values = []
        
        
    def feedforward(self):
        self.a_values = []
        self.neuron_values = []
        actual_layer = deepcopy(self.neurals_input)
        for i in range(len(self.weights)):
            m = np.asmatrix(actual_layer) * np.asmatrix(self.weights[i]) +\
                np.repeat(np.asmatrix(self.biases[i]), repeats=len(actual_layer), axis=0)
            func = np.vectorize(self.functions[i])
            self.a_values.append(m)
            m = func(m)
            self.neuron_values.append(m)
            actual_layer = m.tolist()

        return list(chain(*actual_layer))
    
    def backpropagation(self):
        
        self.e_values = deepcopy(self.a_values)
        n = len(self.e_values)
        
        
        for i in range(n):
            pass
    
    
    def mse(self):
        
        self_results = self.feedforward()
        return mean_squared_error(self_results, self.real_values, squared=True)
    
    def add_layer(self, weights, biases, function):
        
        self.weights.append(weights)
        self.biases.append(biases)
        self.functions.append(function)

In [12]:
xd = n1.feedforward()

In [14]:
n1.a_values

[matrix([[ 111.06637092,   84.79494509,   13.33156857, -183.54391607,
            12.77135816],
         [-101.63449128,  -78.0585516 , -140.00038697,    8.90701141,
          -134.13796834],
         [-108.05949171,  -82.97782543, -144.63204605,   14.72032725,
          -138.57562071],
         ...,
         [ -74.05572696,  -56.94298979, -120.11938687,  -16.04614917,
          -115.08972542],
         [ 108.699908  ,   82.98307297,   11.62563102, -181.40274946,
            11.13687736],
         [  17.17937269,   12.9107703 ,  -54.34976046,  -98.59531877,
           -52.07499712]]),
 matrix([[ 16.33002974,  25.27413412, -23.1531854 ,  15.15216822,
           29.16303449],
         [ -3.29275313, -20.41667585,  16.93187757, -15.60695033,
          -15.7672    ],
         [ -3.29283067, -20.41728836,  16.93605548, -15.60751481,
          -15.76779053],
         ...,
         [ -2.71856906, -15.88058999, -14.00844567, -11.42661445,
          -11.39392147],
         [ 16.32978356,  25.27

In [138]:
func = np.vectorize(derivative_linear)
np.array(n1.feedforward()) - np.array(n1.real_values) * func(np.array(list(chain(*n1.a_values[2].tolist()))))

array([ 4.93476603e-02,  7.79359990e-02,  7.78404816e-02,  5.61446591e-02,
        7.78401954e-02,  5.61433196e-02,  2.53514105e-01,  7.78401954e-02,
        7.78401958e-02,  7.78401954e-02,  7.78401954e-02,  7.78401954e-02,
        6.18418521e-02,  9.29523608e-03,  1.98228554e-01,  2.83214154e-01,
        7.78401954e-02,  5.61433196e-02,  4.93476614e-02,  7.78401954e-02,
        4.93476614e-02, -5.62534850e-01,  7.97469733e-02,  4.93476614e-02,
        4.93476559e-02,  7.78401954e-02,  7.78401954e-02,  5.61433196e-02,
       -3.97235609e-02,  5.63030687e-02,  4.93476614e-02,  7.78401954e-02,
        5.61632754e-02,  5.61433196e-02,  2.83214139e-01,  5.61433196e-02,
        7.78401954e-02,  2.83214154e-01,  5.61433196e-02,  4.93476613e-02,
        7.78401954e-02,  5.70231762e-02,  4.93476614e-02,  2.83214154e-01,
        4.93476484e-02,  2.83214154e-01,  5.61433206e-02,  7.78401954e-02,
        4.93476610e-02,  5.61433196e-02,  7.78401954e-02,  2.83199802e-01,
        4.93476614e-02,  

In [133]:
np.array(list(chain(*n1.a_values[2].tolist())))

array([ 1.60049348e+02, -7.99220640e+01, -7.99221595e+01,  8.00561447e+01,
       -7.99221598e+01,  8.00561433e+01,  2.53514105e-01, -7.99221598e+01,
       -7.99221598e+01, -7.99221598e+01, -7.99221598e+01, -7.99221598e+01,
        8.00618419e+01,  1.60009295e+02,  1.98228554e-01,  2.83214154e-01,
       -7.99221598e+01,  8.00561433e+01,  1.60049348e+02, -7.99221598e+01,
        1.60049348e+02, -5.62534850e-01, -7.99202530e+01,  1.60049348e+02,
        1.60049348e+02, -7.99221598e+01, -7.99221598e+01,  8.00561433e+01,
       -3.97235609e-02,  8.00563031e+01,  1.60049348e+02, -7.99221598e+01,
        8.00561633e+01,  8.00561433e+01,  2.83214139e-01,  8.00561433e+01,
       -7.99221598e+01,  2.83214154e-01,  8.00561433e+01,  1.60049348e+02,
       -7.99221598e+01,  8.00570232e+01,  1.60049348e+02,  2.83214154e-01,
        1.60049348e+02,  2.83214154e-01,  8.00561433e+01, -7.99221598e+01,
        1.60049348e+02,  8.00561433e+01, -7.99221598e+01,  2.83199802e-01,
        1.60049348e+02,  

In [113]:
n1.neuron_values[2].tolist()[0][0]
# n1.neuron_values[nr warstwy].tolist()[nr WEJSCIA][nr neuronu]

160.04934766030013

In [11]:
len(n1.neuron_values)

0

In [56]:
n1.weights[2][0]

[35.663185]

In [5]:
def sigmoid(x):
    e = math.exp((-1)*x)
    return 1/(1+e)

def linear(x):
    return x

# Steps-large

In [7]:
data = pd.read_csv('mio1/regression/steps-large-test.csv')
x = list(data.x)
y_steps_large = list(data.y)

In [8]:
x_steps_large = [[el] for el in x]

## Architektura: dwie warstwy ukryte, po 5 neuronów każda.

In [9]:
def derivative_linear(x):
    return 1

In [10]:
n1 = NeuralNetwork(
    neurals_input = x_steps_large,
    weights = [
        [[92.01574, 70.451454, 66.332375, -83.25549, 63.553905]],
        [[-2.8232336, 19.220058, -1.4210024, -6.060664, 19.102098],
         [-4.154142, 15.317811, -2.1335785, -5.3924274, 15.616502],
         [13.359129, 3.7051284, -2.6084232, 19.427048, 3.5905933],
         [-0.5742619, -4.5367007, 30.944517, -4.1809025, -4.3738713],
         [12.666903, 2.9117405, -2.981745, 18.60491, 2.2477744]],
        [[35.663185],
         [41.10624],
         [-79.27482],
         [44.332226],
         [40.87245]]
    ],
    biases = [
        [-46.003574, -35.46498, -99.89713, -41.42763, -95.71452],
        [-2.718569, -15.8805895, -14.008449, -11.426614, -11.393921],
        [-1.9247388]
    ],
    functions = [
        sigmoid, sigmoid, linear
    ],
    derivatives = [
        derivative_sigmoid, derivative_sigmoid, derivative_linear
    ],
    real_values=y_steps_large
)

In [29]:
n1.weights

[[[92.01574, 70.451454, 66.332375, -83.25549, 63.553905]],
 [[-2.8232336, 19.220058, -1.4210024, -6.060664, 19.102098],
  [-4.154142, 15.317811, -2.1335785, -5.3924274, 15.616502],
  [13.359129, 3.7051284, -2.6084232, 19.427048, 3.5905933],
  [-0.5742619, -4.5367007, 30.944517, -4.1809025, -4.3738713],
  [12.666903, 2.9117405, -2.981745, 18.60491, 2.2477744]],
 [[35.663185], [41.10624], [-79.27482], [44.332226], [40.87245]]]

In [31]:
n1.weights[len(n1.weights)-1]

[[35.663185], [41.10624], [-79.27482], [44.332226], [40.87245]]

In [35]:
len(n1.weights)

3

In [34]:
n1.neurals_input[1]

[-0.604580447659828]

In [ ]:
def backpropagate(neural_network):
    # obliczenie tych wszystkich wartosci a
    

In [116]:
n1.mse()

6.321903482597109

# Square-simple

In [8]:
data = pd.read_csv('mio1/regression/square-simple-test.csv')
x = list(data.x)
y_sq_simple = list(data.y)

In [9]:
x_sq_simple = [[el] for el in x]

## Architektura: dwie warstwy ukryte, po 5 neuronów każda.

In [10]:
n2 = NeuralNetwork(
    neurals_input = x_sq_simple,
    weights = [
        [[-6.8366914, -1.309899, -7.857381, -5.0007024, -5.4391775]],
        [
            [6.494825, 14.298198, 10.50993, -3.0769737, 4.2651587],
            [1.4320817, 1.6100711, 3.084889, 20.4765, 6.853492],
            [4.580216, 8.2289915, 4.503584, -1.817159, 10.2321415],
            [13.247319, 13.200828, 11.405602, -2.907599, 11.668254],
            [8.008364, 11.546485,  8.256871, -3.9173906, 4.917154]
        ],
        [[-49.776226],
         [-47.307373],
         [-49.92147],
         [218.43417],
         [-53.689346]]
    ],
    biases = [
        [11.831797, -2.9020953, 3.0692444, 5.171421, 12.135461],
        [-11.290198, -10.256425, -9.817, 8.219863, -9.890597],
        [53.417557]
    ],
    functions = [
        sigmoid, sigmoid, linear
    ]
)

In [11]:
n2.mse(y_sq_simple)

4.499922868108526